# Generated by Django 2.1.1 on 2018-12-11 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('content', models.TextField()),
                ('content_type', models.CharField(choices=[('text', 'text'), ('tex', 'TEX')], default='text', max_length=10)),
                ('is_right', models.NullBooleanField(default=None)),
                ('answer_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testing.Answer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('token', models.CharField(blank=True, max_length=32, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('finish_date', models.DateTimeField(blank=True, null=True)),
                ('test_started', models.BooleanField(default=False)),
                ('test_reviewed', models.BooleanField(default=False)),
                ('gender', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=20)),
                ('age', models.PositiveIntegerField()),
                ('education', models.CharField(choices=[('basic-general', 'Основное общее образование (9 кл.)'), ('secondary-general', 'Среднее (полное) общее образование (10-11 кл.)'), ('secondary-professional', 'Среднее профессиональное образование'), ('incomplete-higher', 'Неполное высшее (неоконченное образование)'), ('higher', 'Высшее образование'), ('scientific-degree', 'Наличие ученой степени')], max_length=20)),
                ('activity_field', models.CharField(choices=[('economic', 'Экономическая сфера'), ('industrial', 'Промышленная сфера'), ('financial', 'Финансовая сфера'), ('education-science', 'Сфера образования и науки'), ('trading', 'Сфера торговли'), ('services', 'Сфера услуг'), ('agriculture', 'Сельское хозяйство'), ('other', 'Другое')], max_length=20)),
                ('occupation', models.CharField(choices=[('schoolboy', 'Школьник'), ('economic-university', 'Экономический ВУЗ'), ('technical-university', 'Технический ВУЗ'), ('humanitarian-university', 'Гуманитарный ВУЗ'), ('working', 'Работающий'), ('pensioner', 'Пенсионер'), ('other', 'Другое')], max_length=20)),
                ('economy_attitude', models.TextField()),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.QuestionSet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='user_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='account.TestData'),
        ),
    ]
