# Generated by Django 2.1.1 on 2018-12-11 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('is_right', models.BooleanField(default=False)),
                ('text', models.TextField()),
                ('index', models.PositiveSmallIntegerField()),
                ('content_type', models.CharField(choices=[('text', 'text'), ('tex', 'TEX')], default='text', max_length=10)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('content', models.TextField(verbose_name='Question content')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('content_type', models.CharField(choices=[('text', 'text'), ('tex', 'TEX')], default='text', max_length=10)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='QuestionToSet',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('index', models.PositiveSmallIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.Question')),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.QuestionSet')),
            ],
        ),
        migrations.AddField(
            model_name='questionset',
            name='questions',
            field=models.ManyToManyField(through='testing.QuestionToSet', to='testing.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.Question'),
        ),
        migrations.AlterUniqueTogether(
            name='questiontoset',
            unique_together={('question_set', 'index')},
        ),
    ]
