# Generated by Django 2.0.7 on 2018-07-05 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityField',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AnswerVariant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EconomyAttitude',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('answers_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestingModule.AnswerVariant')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('questions', models.ManyToManyField(to='TestingModule.Question')),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=6)),
                ('age', models.PositiveIntegerField()),
                ('activity_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestingModule.ActivityField')),
                ('economy_attitude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestingModule.EconomyAttitude')),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestingModule.Education')),
                ('occupation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestingModule.Occupation')),
                ('question_set_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestingModule.QuestionSet')),
            ],
        ),
    ]
